# Generated by Django 2.2 on 2020-12-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_remove_registration_birthday'),
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join',
            field=models.ManyToManyField(related_name='joined', to='login_app.Registration'),
        ),
    ]
